### ISSUE TITLE
Support for Incoming Webhooks

### ISSUE THREAD

**Issue by maheshsenni** [abdolence/slack-morphism#1]
Thank you creating this really neat library 👏 I really like your implementation of block kit DSL, it is very intuitive.

I am running a report regularly and posting it to my team's slack channel. I am using [Incoming Webhooks](https://api.slack.com/messaging/webhooks) with a json payload to send a Block kit formatted message.  I was wondering if you are planning to support webhooks.

**Comment by abdolence** [comment]
Thanks for your kind feedback. 
Why not, It should be easy to implement, I'll give a try this Monday probably.

**Comment by abdolence** [comment]
Fixed in v1.0.4

**Comment by maheshsenni** [comment]
This is awesome. Thanks!
