### ISSUE TITLE
Unresolved dependency in project

### ISSUE THREAD

**Issue by drewfeelsblue** [abdolence/slack-morphism#142]
Version of sbt-microsites plugin need to be updated(it seems it is possible to use the latest one). Version 1.2.1 uses tpolecat/tut as dependency but all binaries of it are unavailable since May 1, 2021. https://github.com/tpolecat/tut. So sbt can not resolve dependencies of the project

**Comment by drewfeelsblue** [comment]
Here is PR by steward with such update abdolence#130

**Comment by abdolence** [comment]
Hey, thanks for investigation, I noticed something wrong with sbt-microsites, but it shouldn't have affected anyone except me, so I even surprised that someone else noticed it :)

**Comment by abdolence** [comment]
I merged that PR
